name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Select environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run Tests
        run: mvn clean test -Denv=${{ github.event.inputs.ENV }}
